url: "https://gmm.dev/"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
theme: minimal-mistakes-jekyll


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

permalink: pretty
